### ISSUE TITLE
Best pattern for common variables in templates?

### ISSUE THREAD

**Issue by tomtaylor** [unrolled/render#10]
Thanks a lot for this - I'm finding the combination of render and negroni to be a really nice set up.

I've got a question, and maybe it'd be useful to add this to the documentation too. My layout has a header which is common across all pages. I need to add some links to it, and I don't want to pass them into the template's context each time. Is `Funcs` the right place to pass these in?

**Comment by flexd** [comment]
@tomtaylor Did you find a good way of doing this? I need to do something similar as I want to display the logged in user or a link to login as part of my layout.

**Comment by tomtaylor** [comment]
I made a function on my App struct to set up a new context prefilled with the common template data, like the user, country, etc. I didn’t really want to pollute the template functions.
