### ISSUE TITLE
How can I generate JSON from a template

### ISSUE THREAD

**Issue by logicminds** [unrolled/render#2]
I want to generate JSON from a template but I can't see how this is done.  Do I need to read i the template file first and then return output?  The HTML method seems easy why would the JSON be any different?

rd.JSON(w, http.StatusOK, "test")

**Comment by mitar** [comment]
Yes, with text/template it is hard to create JSON files because it is hard to not issue trailing commas.

**Comment by winduptoy** [comment]
@mitar That is one of the 500 reasons that the JSON spec drives me crazy
