### ISSUE TITLE
Tests failing with Layout

### ISSUE THREAD

**Issue by jeffutter** [unrolled/render#23]
I seem to be having an issue I'm not sure how to track down. I'm trying to write some tests with the "testing" library on some negro controllers that use unrolled/render. The issue I am running into is that the tests always fail because the server returns a 500 with the error that the "application" layout can't be found.

If i launch the server and hit it with a browser it works fine. I believe the issue has something to do with the controller being nested in a folder while my layouts are at the top level of my application. I'm guessing the test runner is launching the test from the nested folder and thus render can't resolve the layout.

Is there a way around this? Please let me know if you need more information.

Thanks.

**Comment by unrolled** [comment]
Is you code publicly available somewhere?

**Comment by jeffutter** [comment]
@unrolled Thanks for the quick reply.

I have created a super stripped down version here: https://github.com/jeffutter/unrolledtest

If you go get that that out and: ```go run server.go```

you can hit: http://localhost:3001/cart/checkout in your browser and it shows the application template wrapping the checkout template

If you run the test for the checkout template with: ```go test github.com/jeffutter/unrolledtest/controllers/cart/checkout/```

you get:

```
x
Failures:

  * /Users/jeffutter/go/src/github.com/jeffutter/unrolledtest/controllers/cart/checkout/checkout_test.go
  Line 22:
  Expected 'html/template: "application" is undefined
  ' to contain substring 'Your Cart Is Empty' (but it didn't)!


1 total assertion

--- FAIL: TestIndex (0.00s)
FAIL
FAIL    github.com/jeffutter/unrolledtest/controllers/cart/checkout     0.008s
```

Now.. the test wouldn't pass anyhow. I removed that text as part of what i stripped out.. but It should show the same output as what you get in the browser not matching, instead of an error about the application template.

Thanks again.

**Comment by unrolled** [comment]
If I copy the templates folder into `controllers/cart/checkout/`, it runs like you would expect. Also you could set the Directory option to get it working:

```go 
...
func TestIndex(t *testing.T) {
	template.Render = render.New(render.Options{
		Directory:     "../../../templates",
		Layout:        "application",
		IsDevelopment: true,
	})
...
```

I'm not sure what the best way forward is, but hopefully this helps!

**Comment by jeffutter** [comment]
I haven't had time to get back to this issue lately. I'm still not sure of a good solution. It seems like each controller (or each sub-directory) would need it's own renderer and I would need to change the path depending on wether or not I am running in test mode or not. Perhaps I am doing something that isn't idiomatic GO here?

Thoughts?

**Comment by unrolled** [comment]
The way I would approach this would be to create a single `render` instance, and inject it into the controllers as needed. 

```go
func main() {
    rndr := render.New()
    ...
    http.HandleFunc("/cart", CartHandler(rndr))
    ...
}

...

func CartHandler(rndr *render.Render) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        // Use rndr here like normal.	
    })
}
```

This would require you reworking you project structure, but it may be for the best. Then when you write tests for each handler, you can create the render object and pass it in.
