### ISSUE TITLE
Response Streams

### ISSUE THREAD

**Issue by codingrogue** [unrolled/render#24]
Is there a way to use r.JSON with a JSON Decoder to make use of streams? I read that usual marshaling is memory hungry on huge responses.

Nevertheless VERY clean and useful package! Keep it up!

**Comment by unrolled** [comment]
I'm looking into this right now, and it looks promising! I'll let you know more in a day or two.

**Comment by unrolled** [comment]
@codingrogue I've added a new option `render.StreamingJSON`. Have a look at the README.md for the details!

**Comment by codingrogue** [comment]
Awesome! Thx a lot.
