### ISSUE TITLE
Render to a Buffer Pool

### ISSUE THREAD

**Issue by elithrar** [unrolled/render#27]
Firstly: excuse any issue spam and (hopefully) any following PRs. I'm digging around your library—which I've been aware of for a while and have liked quite a bit—in order to *finally* get a side project finished instead of getting caught writing too much of my own junk!

Anyway:

* Right now `Render.execute` writes to a static `bytes.Buffer`: https://github.com/unrolled/render/blob/v1/render.go#L345
* As does HTML.Render: https://github.com/unrolled/render/blob/v1/engine.go#L172
* Writing to a buffer pool nets us some garbage savings.

We changed over to a buffer pool on the [martini-contrib/render](https://github.com/martini-contrib/render/pull/33) library to which you're a contributor and this approach is what I've been using for a while in other internal projects.

Implementation approach:

* Had first considered adding a `*bpool.BufferPool` as a private field to the `Render` type, but the `Engine` interface prevents us from adding another argument to the `Render(http.ResponseWriter, interface{}) error` method (without breaking the API). That method on the `HTML` type has a fixed buffer we can't get to with this constraint.
* Workaround: Create a package-level global `var bufPool *bpool.BufferPool` and assign a `bpool.NewBufferPool(64)` to it in `func New(options ...Options) *Render`. 
* Replace any `bytes.Buffer` initialisations with a `buf := bufPool.Get()` and an associated `bufPool.Put()` once done. We avoid `defer bufPool.Put()` since defer has a slight performance hit that'd be nice to avoid.

Let me know if this looks good and I'll submit a PR.

**Comment by unrolled** [comment]
Hey @elithrar, no issues with spam here... love the interest and contributions! I've looked into this before and thought it was a great idea. My one small issue is that we would be introducing a new package dependency. It's not horrible or show stopping, but I really like packages to be complete standalone libraries. Would it be possible to pull in the relevant parts of `bpool` into a single file that would be part of the package?

**Comment by elithrar** [comment]
Perfect - and yep, I can do that. Will send a PR tonight (~12 hours from now in Australian time).
