### ISSUE TITLE
Empty slice rendered as "null"

### ISSUE THREAD

**Issue by solher** [unrolled/render#29]
Hi,
I'm currently facing a really weird problem that I don't understand.
In a controller, I get a url slice (urls) from another function and I render it.
In the case I get an empty slice, it is rendered as "null" in the JSON.
The thing is, when I pass a freshly created empty slice ([]Url{}), it is well rendered as "[]".
You're going to tell me that the problem comes from the "urls" var but all the following commands give the same results for both the "urls" var and the fresh slice.
The only difference is when I try to render with the one or the other at the end.

fmt.Println(reflect.TypeOf(urls))
fmt.Println(reflect.TypeOf([]Url{}))

fmt.Println(reflect.ValueOf(urls))
fmt.Println(reflect.ValueOf([]Url{}))

fmt.Println(len(urls))
fmt.Println(len([]Url{}))

render := render.New()
render.JSON(w, http.StatusOK, urls)
render.JSON(w, http.StatusOK, []Url{})

Do you have any ideas ?
Thanks.

**Comment by elithrar** [comment]
The short answer: http://play.golang.org/p/TFdWXo3AOq

Slightly longer

   - an initialised slice or map (in this case, the url.Values map) with a
   length but no elements is not nil and therefore just empty - hence the
   empty JSON array
   - an uninitialised slice or map *is* nil - hence it converts to a JSON
   null

Hope that's clear.

**Comment by solher** [comment]
Oh. So an uninitialised slice has a len of 0 ? That's what bothered me.

Perfect, thanks.

**Comment by solher** [comment]
But in that case, how can I find out if the slice is uninitialised if it has the same type, the same value and the same length than an initialized one ? How can I debug it ?

**Comment by elithrar** [comment]
Check the length. Although `sliceA` has a length of 10, if there are no elements it will return 0.

```go
package main

import "fmt"

var sliceA = make(map[string]string, 10)
var sliceB = make(map[string]string, 10)
var nilA map[string]string
var nilB map[string]string

func main() {
	// Is nil
	if nilA == nil {
		fmt.Println("nilA is nil!")
	}

	// Not nil
	if sliceA == nil {
		fmt.Println("sliceA is nil")
	}

	if len(sliceA) == 0 && len(nilA) == 0 {
		fmt.Println("both are empty")
	}
}
```

Output:
```go
nilA is nil!
both are empty
```
