### ISSUE TITLE
Echo integration example error

### ISSUE THREAD

**Issue by pandex** [unrolled/render#30]
The Echo integration example, copied and pasted as is, gives the following error at run:

    cannot use c.Response (type func() *echo.Response) as type http.ResponseWriter in argument to     r.JSON:
	    func() *echo.Response does not implement http.ResponseWriter (missing Header method)

(using echo and render updated/downloaded as of now.)

**Comment by unrolled** [comment]
Great catch! I'll update the docs later today.

**Comment by unrolled** [comment]
Alright, updated! Looks like the method signature changed since I wrote this up initially.
