### ISSUE TITLE
bufPool desacred but not used

### ISSUE THREAD

**Issue by cgyy** [unrolled/render#31]
if bufPool == nil {
		bufPool = NewBufferPool(64)
	}
the bufPool is not used

**Comment by elithrar** [comment]
See https://github.com/unrolled/render/blob/master/engine.go#L83 and https://github.com/unrolled/render/blob/master/engine.go#L93

**Comment by cgyy** [comment]
( ⊙ o ⊙ ) 囧

**Comment by cgyy** [comment]
I'm sorry ,this issues should be closed
