### ISSUE TITLE
Add a example using render as a global variable to README

### ISSUE THREAD

**Issue by Immortalin** [unrolled/render#32]
It would be great if you could add a example on using the render package as a global variable i.e. outside of main. Before I discovered [this](https://github.com/unrolled/render/issues/7), I had faced a lot of issues in trying to get Render to work when my handlers are not in main.

**Comment by elithrar** [comment]
Are you defining your handlers in init() or elsewhere?

**Comment by Immortalin** [comment]
I put the initialisation of render.Render in a separate function that was called by main() but I keep receiving an "undefined" error when I used it in my handlers. Stack is Negroni+ Httprouter.

**Comment by elithrar** [comment]
Using `*render.Render` as a global is pretty straightforward (you probably
found out), but globals aren't ideal.

You can certainly pass it explicitly with Negroni/httprouter though: have
you got a snippet of what you attempted so far?


Using `*render.Render` as a global is /okay/, but not ideal.

**Comment by Immortalin** [comment]
```Go
func main() {
 	router := httprouter.New()
	ren := render.New(render.Options{
		Extensions: []string{".html"},
	})
 	n := negroni.Classic()
 	router.GET("/", HomeHandler)
 	router.GET("/createbook", CreateHandler)
 	n.UseHandler(router)
	n.Run(":3001")
 }

func CreateHandler(w http.ResponseWriter, r *http.Request, p httprouter.Params) {
	ren.HTML(w, http.StatusOK, "example", nil)
}

**Comment by elithrar** [comment]
A simple approach is to use a closure:

```go
func CreateHandler(ren *render.Render) httprouter.Handle {
   return httprouter.Handle(func(w http.ResponseWriter, r *http.Request, p httprouter.Params) {
        ren.HTML(w, http.StatusOK, "example", nil)
    })
}
```

... and then in your router:

```go
func main() {
    router := httprouter.New()
    ren := render.New(render.Options{
        Extensions: []string{".html"},
    })
    n := negroni.Classic()
    router.GET("/", HomeHandler(ren))
    router.GET("/createbook", CreateHandler(ren))
    n.UseHandler(router)
    n.Run(":3001")
 }
```

This makes it clear where `ren` is used. If you end up with lots of 'services' like a renderer, a database connection, a configuration struct, etc you can compose them into a struct and pass a pointer to that instead.

**Comment by Immortalin** [comment]
@elithrar thank you!

**Comment by Immortalin** [comment]
@elithrar is using closures worth the trouble since global variables require less code?

**Comment by Immortalin** [comment]
@elithrar I am getting a "cannot define new methods on non-local type render.Render" when using closures.

**Comment by elithrar** [comment]
Can you show me what you have? Sounds like you're creating methods, not
closure functions.

**Comment by elithrar** [comment]
And yes, globals *are* simple. They're not terrible, but beware of the
challenges when you have 5,6,7,15 globals and it becomes hard to know what
is declared where ;)

**Comment by Immortalin** [comment]
I think the problem's fixed, just a mistake on my part while using git. ;)

**Comment by Immortalin** [comment]
Do you have any suggestions on how to use the same method with the SQL package? Currently I am declaring all my SQL pointers as global variables as that is what most tutorials seem to do.

**Comment by elithrar** [comment]
Take a look at
https://robots.thoughtbot.com/interface-with-your-database-in-go and
http://www.alexedwards.net/blog/organising-database-access#using-an-interface

**Comment by Immortalin** [comment]
Thanks!
