### ISSUE TITLE
How can I tell which templates exist in a render object?

### ISSUE THREAD

**Issue by flimzy** [unrolled/render#33]
Prior to using unrolled/render, I had some code like this:

    if templates.Lookup(templateName + ".html") == nil {
        templateName = "index"
    }

To check whether a particular template existed, and if not to fall back to the "index" template.

As the template.Template object is not exposed through the Render object, I don't see any way to accomplish the same thing.  Is there a way I'm not seeing, or can this be added?

**Comment by unrolled** [comment]
This isn't possible right now. But a PR would be gladly accepted!

**Comment by flimzy** [comment]
I'd be happy to work on a PR.  But how should that functionality be added?

By far the easiest way to offer that functionality would be simply to expose the underlying template.Template object.  Is that wise?  You've clearly decided to hide that from the API at the moment...

An alternate, though less flexible, way to do that would be to add a simple method to check for the existence of a template--a thin wrapper around template.Lookup().

Which do you prefer?
