### ISSUE TITLE
blocks: how to handle undefined templates and subfolders?

### ISSUE THREAD

**Issue by jeromenerf** [unrolled/render#36]
"blocks" are new and well appreciated. May it be for css or scripts, we can use `{{ block "css" }}` to load `css-templatename` when `templatename` is current in layout. 

Two minor remarks though: 

- for now, if the `blockname-template.tmpl` file is missing, a `template: layout:9:7: executing "layout" at <block "blockname">: error calling block: html/template: "blockname-template" is undefined` error will be triggered. Should we try to handle this kind of error in templates / layout, create as many blocks as necessary or should "render" return an empty template when the required file is missing?

- if one uses subfolders for templates (`resources.tmpl`, `resource.tmpl`, `admin/resources.tmpl`, `admin/resource.tmpl`), blocks are intended to be found at `blockname-subfolder/templatename.tmpl` over what feels more logical to me `subfolder/blockname-templatename.tmpl`. Am I doing it wrong?

**Comment by unrolled** [comment]
Hey @jeromenerf, sorry for the delay on this! 

1. I would rather see an error than an empty string myself. This would keep it consistent with normal templates... if it doesn't exist, you'll get an error.
2. You are correct... I'll fix this issue up asap!

I've also been keeping my eye on Go's new `block` keyword which could be very useful: https://github.com/golang/go/commit/12dfc3bee482f16263ce4673a0cce399127e2a0d

**Comment by jeromenerf** [comment]
Thanks @unrolled, what would be your recommendation to handle "missing blocks"? I like the idea of layouts and optional blocks coming alongside a given template to handle css, scripts, header tags and so on. 

The annoying thing, IIRC, with go templates is that we can't handle errors to decide whether to stop or continue.

**Comment by blachniet** [comment]
I like the idea of optional blocks as well. In fact, I think the blocks should be optional by default. 

Other templating engines treat the blocks as optional by default (Jade and Razor are the ones that I have experience with). Not every one of my templates will need to add custom scripts to my `{{ block "scripts" }}` in my layout. It's annoying to have to and an empty `{{ block "scripts-home" }}{{end}}` to every template, even if it doesn't need to add scripts.

I think they should be optional by default. The behavior can be configured with a property like `Options.RequireBlocks`.
