### ISSUE TITLE
Rendering the HTML of a string

### ISSUE THREAD

**Issue by Ozzadar** [unrolled/render#41]
Hey,

I'm sure there's a way to do it but I cant seem to find it anywhere in the docs.

is there a way to pump for example: 
<//a href="link">link</a>

and not have the renderer escape the html and properly display a link?

I was using beego and they had a str2html that did this and it seems like a pretty common feature that Im probably just being dense and not seeing.

Thanks!
-Ozzadar

**Comment by unrolled** [comment]
Hey Ozzadar,

There is no built in function to handle this use case, but you can implement a custom template function yourself:

``` go
render := New(Options{
    ...
    Funcs: []template.FuncMap{
        {
            "str2html": func(raw string) template.HTML {
                return template.HTML(raw)
            },
        },
    },
    ...
})
```
And then call it like this:
``` html
{{ str2html "<//a href=\"link\">link" }}
```

Does this help?

**Comment by Ozzadar** [comment]
Absolutely! Thanks a bunch!

I have one more question actually I tried a

{{if eq .Username ""}}

And it gave me incompatible type. How do I check for equality? :)

**Comment by unrolled** [comment]
That looks right to me... is `Username` for sure a string?

**Comment by Ozzadar** [comment]
Yeah, as a member of a struct I'm passing in

User {
Username string 'sql:...'
...}

c.HTML(rw,r,user)

Template::

{{if eq .Username ""}}

Error: incompatible type

**Comment by Ozzadar** [comment]
I found the problem. When returning .Username it's being returned as a []byte array.

I implemented a function similar to str2html that takes the []byte array and returns it as a string

```
 "string": func(raw []byte) template.HTML {
                return template.HTML(string(raw))
 }
```

**Comment by unrolled** [comment]
Ahhh, that would do it! Can this issue be closed now?

**Comment by Ozzadar** [comment]
" {{template "header"}} section, which seems like its not getting the variable passed into it.

Is there a way to accomplish this, or a subtag I should be calling? "

if you have a solution to this, yes, it can be closed. Otherwise, if you don't have a solution. maybe ? (Depending if its a html/template thing or a render thing ?)

**Comment by Ozzadar** [comment]
Ok, you can close this now. I'm a dummy and figured it out :D

Turns out I needed to 

```
{{template header .}}
```

to pass in the variables :)
