### ISSUE TITLE
How can i get number of containers or images?

### ISSUE THREAD

**Issue by erolg** [unrolled/render#43]
I tried "cap" and "len" command but both of these didn't help.

```len(client.ListContainers(docker.ListContainersOptions{All: true}))```
```cap(client.ListImages(docker.ListImagesOptions{All: true}))```

How can i get number of containers or images?

**Comment by elithrar** [comment]
@erolg I think this might be on the wrong repository? It's not clear what you're trying to do or how this relates to template rendering without a more complete example.

**Comment by erolg** [comment]
Yes, i just realize that. I am sorry.
