### ISSUE TITLE
Go 1.6 blocks conflict

### ISSUE THREAD

**Issue by anoland** [unrolled/render#47]
It seems that the 1.6 release of go will have a block keyword. Are there plans to update render to work with the next version?

**Comment by unrolled** [comment]
Oh boy, thats not good at all! I'm working on a fix and will get something out before 1.6 is released.

Thanks for bring this to my attention!

**Comment by unrolled** [comment]
Hey @anoland, checkout this pull request #48. Let me know if you have any thoughts!

**Comment by pjebs** [comment]
What happened to `Go 1.*`'s backward compatibility promise?

**Comment by elithrar** [comment]
@pjebs The Go1 compat. promise means that existing code will compile on new releases [short of security fixes]. The new template blocks don't change that.

**Comment by unrolled** [comment]
Merged #48.
