### ISSUE TITLE
Render to mailer?

### ISSUE THREAD

**Issue by silasb** [unrolled/render#51]
I'm interest in rendering to a mailer. AFAIK I can't easily do this because it is setup to write to http.ResponseWriter directly.  Any ideas for getting this to work with a mailer?

**Comment by unrolled** [comment]
Unfortunately I have no suggestions for you. render is tied very tightly to the `http` package (specifically `http.ResponseWriter`). Sorry!

**Comment by omeid** [comment]
`http.ResponseWriter` is an interface.

**Comment by unrolled** [comment]
As @omeid eluded to, you could create a struct that satisfies the [http.ResponseWriter](https://golang.org/pkg/net/http/#ResponseWriter) interface. The `Header` and `WriteHeader` funcs could then be ignored (implemented as dummy funcs) leaving the `Write` func for your mailer.

**Comment by seailly** [comment]
Just in case anyone hits this page wanting the HTML render to return a string [here is a gist](https://gist.github.com/seailly/4d9a9102223595e10f396ad114bd11ac) satisfying the `http.ResponseWriter` interface.
