### ISSUE TITLE
fasthttp support?

### ISSUE THREAD

**Issue by raitucarp** [unrolled/render#52]
Would you like to plan support for fasthttp?  Goji (I hear they will switch to fasthttp), echo v2 and Iris are based on fasthttp.

**Comment by elithrar** [comment]
Goji isn't switching to fasthttp :)

**Comment by raitucarp** [comment]
@elithrar yes, you are right. they just consider the issue related to fasthttp, and don't want to switch yet.

**Comment by unrolled** [comment]
I've briefly looked into `fasthttp`, but do not plan on supporting it. If anyone is interested in submitting a PR with the integration, I'd be happy to help and review the implementation.

**Comment by raitucarp** [comment]
OK. Thanks for your confirmation.
