### ISSUE TITLE
Set custom JSON Content-Type

### ISSUE THREAD

**Issue by chocolatkey** [unrolled/render#60]
I am using this together with Mux & Negroni (Go 1.8) and would like to set a custom content-type header when rendering JSON, `application/vnd.api+json` because I am writing an API complying with the [JSON API format](http://jsonapi.org/format/). There's an option for setting HTML type as in the README (e.g. `HTMLContentType: "application/xhtml+xml"`), but none for JSON. How would I go about setting it?

**Comment by unrolled** [comment]
There currently isn't a way to set the json content type... but I'll add in the option to do so shortly!

**Comment by unrolled** [comment]
Ok, you can now use `JSONContentType` to set the json content type. Let me know how it works out!

**Comment by chocolatkey** [comment]
Thanks, works great!
