### ISSUE TITLE
Problem is http response

### ISSUE THREAD

**Issue by jjkim0816** [unrolled/render#62]
Hi, I am Kim Jeong Jin.
I have a ask you about problem.
When I get a http response, I use unrolled render HTML api.

I make html template under code.
``` go
out += `<ul class="jqueryFileTree" style="display: none;">`
files, _ := ioutil.ReadDir(dir)
for _, f := range files {
		if false == noHidden || f.Name()[0] != '.' {
			p := path.Join(dir, f.Name())
			if true == f.IsDir() {
				out += fmt.Sprintf(`<li class="directory collapsed"><a href="#" rel="%s">%s</a></li>`, p+"/", f.Name())
			} else {
				out += fmt.Sprintf(`<li class="file ext_%s"><a href="#" rel="%s">%s</a></li>`, path.Ext(f.Name())[1:], p, f.Name())
			}
		}
	}
out += `</ul>`
```

And I  call a "func (r *Render) HTML(w io.Writer, status int, name string, binding interface{}, htmlOpt ...HTMLOptions) error"

But html tag changed from "<" to " & lt ; "

How do I set binding parameter for text html tag?

**Comment by unrolled** [comment]
The `html/template` package in Go will autoescaping for you (see explanation [here](https://golang.org/pkg/html/template/).

An easy way to get around this is to create a `htmlSafe` function, but just be sure the content can be trusted to avoid injection attacks:

``` go
func main() {
	r := render.New(render.Options{
		Funcs: []template.FuncMap{
			{
				"htmlSafe": func(text string) template.HTML {
					return template.HTML(text)
				},
			},
		},
	})
	mux := http.NewServeMux()

	mux.HandleFunc("/html", func(w http.ResponseWriter, req *http.Request) {
		r.HTML(w, http.StatusOK, "example", "<i>World</i>")
	})

	http.ListenAndServe("127.0.0.1:3000", mux)
}
```

``` html
<h1>Hello {{htmlSafe .}}.</h1>
```
