### ISSUE TITLE
BufferPool leads to wasted memory

### ISSUE THREAD

**Issue by nsmith5** [unrolled/render#85]
## Problem

The current buffer pool appears to buffer writes for HTML templating. While the buffers are `Reset` upon resubmission to the pool, this [doesn't free the underlying memory](https://pkg.go.dev/bytes#Buffer.Reset). The result in a long running web server is that the buffer pool contains ~64 * the largest template rendered.

This size can get unreasonable in applications like Gitea where some pages might contain sizable assets like pictures. My heap profiles show something like 500MiB of heap space just because of this.

## Possible solutions

This buffer pool probably isn't needed at all. Simply push the concern of write buffering to the calling library. In fact, the most likely writer to be used with this library _already buffers writes_: [`http.ResponseWriter`](https://stackoverflow.com/questions/26033853/will-http-responsewriters-write-function-buffer-in-go). 

If a buffer pool is _really_ needed, perhaps use something like [this sized buffer pool](https://github.com/oxtoacart/bpool/blob/master/sizedbufferpool.go) that trims down buffers that grow past a certain size so that the pool can't grow unchecked.

**Comment by unrolled** [comment]
@nsmith5 I just merged your PR and rolled a release (v1.1.0). Do you want to try it out in production for a while before closing this issue?

**Comment by nsmith5** [comment]
Memory footprint drops as expected. This was merged into Gitea downstream here https://github.com/go-gitea/gitea/pull/15581
