### ISSUE TITLE
Unicode escaping

### ISSUE THREAD

**Issue by pkieltyka** [unrolled/render#9]
Just to bring to your attention something that causes issues for browsers to parse JSON responses.. see: https://github.com/pressly/render/commit/1581cb3f045ba16b5fe9eaa39de2ab5e923b9d01

this isn't quite the best fix, just wanted to reference the article, which then references: https://github.com/clbanning/mxj/blob/master/json.go#L20

**Comment by unrolled** [comment]
@pkieltyka Better late than never, but a PR got merged in today that fixes this!
