### ISSUE TITLE
Example of Embedded FS support is missing package name

### ISSUE THREAD

**Issue by paulwalk** [unrolled/render#95]
I think that in the example:

```go
r := render.New(render.Options{
    Directory: "templates",
    FileSystem: &EmbedFileSystem{
        FS: embeddedTemplates,
    },
    Extensions: []string{".html", ".tmpl"},
})
```
the reference to `&EmbedFileSystem` should be `&render.EmbedFileSystem`

This will make more sense to people using the library in their own package i.e. not called "render").

**Comment by unrolled** [comment]
Just updated the docs, thanks for pointing this out!

**Comment by paulwalk** [comment]
Thanks! I'm getting real value out of this package - thanks for developing this :-)
