### ISSUE TITLE
UnescapeHTML can render un-parseable JSON

### ISSUE THREAD

**Issue by aaronlisman** [unrolled/render#98]
If you try to render JSON with a string field that has, say, some javascript that has a string with the characters for an escaped bracket (`let foo = "\\u003c"`), the resulting JSON isn't valid because of the global replace here: https://github.com/unrolled/render/pull/20/commits/cb1d010d27bf5115289fb882e049043df41d8410#diff-faa39773718bee2c453eb6825bcc4dc5766eff99ab928f1827ddba95d18d15e2R91

At the very least I don't think it should be set to `true` by default.

Example test:

```
func TestSimple(t *testing.T) {
	for _, unescapeHTML := range []bool{true, false} {
		t.Run(fmt.Sprintf("UnescapeHTML: %v", unescapeHTML), func(t *testing.T) {
			script := `let foo = "\\u003c"`
			jsonStruct := struct {
				Script string `json:"script"`
			}{
				Script: script,
			}

			r := render.New(render.Options{UnEscapeHTML: unescapeHTML})
			rec := httptest.NewRecorder()
			require.NoError(t, r.JSON(rec, 200, jsonStruct))
			unrolledBytes := rec.Body.Bytes()

			unmarshalledJson := struct {
				Script string `json:"script"`
			}{}

			require.NoError(t, json.Unmarshal(unrolledBytes, &unmarshalledJson))
			assert.Equal(t, script, unmarshalledJson.Script)
		})
	}
}
```

```
=== RUN   TestSimple/UnescapeHTML:_true
    response_test.go:38: 
        	Error Trace:	response_test.go:38
        	Error:      	Received unexpected error:
        	            	invalid character '<' in string escape code
        	Test:       	TestSimple/UnescapeHTML:_true
```

**Comment by unrolled** [comment]
> At the very least I don't think it should be set to `true` by default.

I just confirmed that the default is `false`: https://github.com/unrolled/render/commit/d8f29420ae69732c19ffe2151155f9a0b75f40eb#diff-73ed0a2f4024985d66f2c62d92f727d915198b4bef8bec9d1093854226506806L115

If I remember correctly the thought was that this feature should be opt-in only as it does have the potential to corrupt the final json.

**Comment by aaronlisman** [comment]
Yeah, sorry, I got a bit confused and had apparently seen the `true` default in one of *our* helper libraries' code. Still, it's concerning that this is easy to turn on and could start breaking things. Is it not possible to do the unescaping earlier on in the encoding process? The JSON encoder itself has an option to disable this right? https://pkg.go.dev/encoding/json#Encoder.SetEscapeHTML

**Comment by unrolled** [comment]
No way, I didn't know that was added!! I'll do a refactor to use the builtin escaping. Thanks for bring this up!
